name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: hello-cluster    # Add your cluster name here.
  GKE_ZONE: europe-central2     # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test     # Add your deployment name here.
  IMAGE: static-site

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker image
        run: |
          docker build . --file Dockerfile --tag my-python-app
          docker tag my-python-app ${{ secrets.DOCKER_USERNAME }}/simple-flask-cicd:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-flask-cicd:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Get the GKE credentials so we can deploy to the cluster
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION"


      - name: Set up Kustomize
        run: |
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Update Kubernetes resources
        run: |
          cd k8s
          kustomize edit set namespace simple-flask
          kustomize edit set image simple-flask-cicd=$DOCKER_USERNAME/simple-flask-cicd:latest
          cat kustomization.yaml

      - name: Deploy updated Kubernetes resources
        run: |
          kubectl apply -k k8s/ 