name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: hello-cluster
  GKE_ZONE: europe-central2
  DEPLOYMENT_NAME: gke-test
  IMAGE: simple-flask-cicd

jobs:
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Build and Push Docker image
  #       run: |
  #         docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE }}:latest
  #         docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE }}:latest

  deploy:
    # needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
      - name: Get the GKE credentials so we can deploy to the cluster
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Set up Kustomize
        run: |
          curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.4.1/kustomize_v4.4.1_linux_amd64.tar.gz" | tar xz
          chmod u+x ./kustomize

      - name: Update Kubernetes resources
        run: |
          cd k8s
          kustomize edit set namespace simple-flask
          kustomize edit set image ${IMAGE}=${{ secrets.DOCKER_USERNAME }}/${IMAGE}:latest
          cat kustomization.yaml
      - name: Create Namespace if not present
        run: |
          kubectl get namespaces simple-flask || kubectl create namespace simple-flask
      - name: Deploy updated Kubernetes resources
        run: |
          kubectl apply -k k8s/
